title: Gistbook
author: Tomáš Krupka
description: a simple way to organize your Gists in one place - Gistbook
url: https://krupkat.github.io
baseurl: "/gistbook"

theme: no-style-please

theme_config:
  appearance: "auto"
  back_home_text: "home"
  date_format: "%Y-%m-%d"
  show_description: false

collections:
  tags:
    output: true
    permalink: /:collection/:name

feed:
  excerpt_only: true

exclude:
  - bootstrap.py
  - requirements.txt
  - LICENSE
  - README.md